### ISSUE TITLE
Improve feedback processing in robot.cpp

### ISSUE THREAD

**Issue by JAndringa** [RoboTeamTwente/roboteam#11]

**Comment by JAndringa** [comment]
not all feedback given by the robot is used. More information from the robots give more accurate calculations so add as many feedbacks here as possible. If you're not sure what feedback we receive: take a look at the proto files.

**Comment by umer99roboteam** [comment]
Make list of feedback received and which ones can be used

**Comment by umer99roboteam** [comment]
Integrate capacitor charged into dealer

**Comment by JornJorn** [comment]
After discussing with embedded+control, only capacitor charged could be useful to use right now.
Will discuss with electronics if it's useful or if it will charge quick enough to ignore it

**Comment by JornJorn** [comment]
Right now, there is nothing in robot feedback that we think can be usefull to also use
