### ISSUE TITLE
check for robot optional in kick.cpp

### ISSUE THREAD

**Issue by JAndringa** [RoboTeamTwente/roboteam#14]

**Comment by JAndringa** [comment]
The kick skill uses a robot optional. But it never gets checked for the case where there is no robot. This could lead to crashes so add a check.

**Comment by JornJorn** [comment]
![image](https://github.com/RoboTeamTwente/roboteam/assets/81434299/7e0c05d1-d673-4e0e-8276-f2bf3aae28d8)
Someone fixed this and didn't close the issue :P
