### ISSUE TITLE
Match dribbler velocity with ball velocity when receiving a ball

### ISSUE THREAD

**Issue by supertom01** [RoboTeamTwente/roboteam#29]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
When robots receive a ball, they currently just turn on the dribbler (i.e. the dribbler is a boolean value). However, as indicated by tests that have been conducted in the previous year (results can be found in the ETDP from 2022) the most optimal way would be to match the angular velocity of the dribbler with that of the ball. 

Even though there is no proper dribbler control yet, it should be doable to have some reliable dribbler velocity, due to the lack of friction. Once the ball has made contact the speed can just be gradually increased to the maximum dribbler speed.

**Describe alternatives you've considered**
There are not really any alternatives at the moment

**Additional context**

**Comment by JornJorn** [comment]
We tested this year again, and we have some dribbler control on the robot. All we send right now to the robot is to turn on/off. Don't think this is needed anymore
