### ISSUE TITLE
Fix controlModule.cpp

### ISSUE THREAD

**Issue by JAndringa** [RoboTeamTwente/roboteam#6]

**Comment by JAndringa** [comment]
A lot the functions in controlModule use the optional view of robot, but not every function utilizes this. Or in some cases it is even completely redundant as the robot gets checked before the function is called. In my opinion this is very sloppy code and should be changed. Find out which functions need to utilize the optional type, also make sure they actually do utilize it, and which functions do no need the optional type and remove it from them.

The rest of the TODO's can be removed.

**Comment by JornJorn** [comment]
All fixed somewhere at the first half of 23/24. Not sure in which commit.
Optional is only used for addRobotCommand, since this is called in skill which doesn't have a robotview when initialized.
