### ISSUE TITLE
infinite while loop in Trajectory2D

### ISSUE THREAD

**Issue by JAndringa** [RoboTeamTwente/roboteam#62]
Path planning enters an infinite while loop sometimes.
One way to replicate this bug is:
  1. Start AI in either simulator or basestation
  2. uncheck the "use referee" box
  3. force a play
  4. check the "use referee" box again
  5. boom infinite while loop until you force a play again
Still no idea why this happens though but it is kind of annoying

**Comment by JornJorn** [comment]
Doesn't happen anymore. Not sure when it was fixed.
