### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by luukieboy** [RoboTeamTwente/roboteam#96]
**Describe the bug**
Primary AI crashed when testing. 

**To Reproduce**
??????

**Expected behavior**
Not crash

**Screenshots**
![Screenshot from 2023-10-03 11-07-02](https://github.com/RoboTeamTwente/roboteam/assets/142982901/fc0815b9-a1ca-4158-a055-a89b83203765)

**System**
 - Ubuntu 22.04

**Comment by JornJorn** [comment]
I feel like this was just us when starting the year, since it has never happens afterwards and only happened on the branch we created when fooling around at the start of the year. Closing for now.

**Comment by JornJorn** [comment]
I forgot to click close
